name: Deploy ISA Metrics Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy-to-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Because your 'assets' directory is set to "." in wrangler.jsonc,
      # Wrangler will automatically grab index.html and bundle it with _worker.js!
      - name: Deploy using Cloudflare Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy